SpotOn.App/Models/ErrorViewModel.cs
namespace SpotOn.App.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SpotOn.App/Models/SuggestMusicViewModel.cs
namespace SpotOn.App.Models
{
    public class SuggestMusicViewModel
    {
        public string FavouriteArtistIds { get; set; }
        public string FavouriteTrackIds { get; set; }
        public string FavouriteGenres { get; set; }
    }
}

SpotOn.App/Controllers/SpotifyController.cs
using Microsoft.AspNetCore.Mvc;
using SpotOn.Core;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SpotOn.App.Controllers
{
    [Route("api/[controller]/[action]")]
    [ApiController]
    public class SpotifyController : ControllerBase
    {
        private readonly ISpotifyClient spotify;

        public SpotifyController(ISpotifyClient spotify)
        {
            this.spotify = spotify;
        }

        [HttpGet]
        public async Task<ActionResult<IEnumerable<Artist>>> FindArtists(string input)
        {
            List<Artist> result = new List<Artist>();
            if (!string.IsNullOrWhiteSpace(input))
            {
                await spotify.Authorize();
                IEnumerable<Artist> artists = await spotify.FindArtists(input);
                result.AddRange(artists);
            }
            return result;
        }

        [HttpGet]
        public async Task<ActionResult<IEnumerable<Track>>> FindTracks(string input)
        {
            List<Track> result = new List<Track>();
            if (!string.IsNullOrWhiteSpace(input))
            {
                await spotify.Authorize();
                IEnumerable<Track> tracks = await spotify.FindTracks(input);
                result.AddRange(tracks);
            }
            return result;
        }

        [HttpGet]
        public async Task<ActionResult<IEnumerable<Genre>>> GetGenres()
        {
            await spotify.Authorize();
            return (await spotify.GetGenres()).ToList();
        }

        [HttpGet]
        public async Task<ActionResult<IEnumerable<Track>>> GetRecommendationsForNames(string artistName = null, string trackName = null, string genreName = null)
        {
            List<Track> result = new List<Track>();
            if (!string.IsNullOrWhiteSpace(artistName) || !string.IsNullOrWhiteSpace(trackName) || !string.IsNullOrWhiteSpace(genreName))
            {
                await spotify.Authorize();

                string artistId = null;
                if (!string.IsNullOrWhiteSpace(artistName))
                {
                    IEnumerable<Artist> inputArtists = await spotify.FindArtists(artistName);
                    artistId = inputArtists.FirstOrDefault()?.Id;
                }

                string trackId = null;
                if (!string.IsNullOrWhiteSpace(trackName))
                {
                    IEnumerable<Track> inputTracks = await spotify.FindTracks(trackName);
                    trackId = inputTracks.FirstOrDefault()?.Id;
                }

                string genreId = null;
                if (!string.IsNullOrWhiteSpace(genreName))
                {
                    IEnumerable<Genre> inputGenres = await spotify.FindGenres(genreName);
                    genreId = inputGenres.FirstOrDefault()?.Name;
                }

                if (artistId != null || trackId != null || genreId != null)
                {
                    IEnumerable<Track> tracks = await spotify.GetRecommendations(new[] { artistId }, new[] { trackId }, new[] { genreId });
                    result.AddRange(tracks);
                }
            }
            return result;
        }
    }
}

SpotOn.App/Controllers/SuggestMusicController.cs
using Microsoft.AspNetCore.Mvc;
using SpotOn.App.Models;
using SpotOn.Core;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SpotOn.App.Controllers
{
    public class SuggestMusicController : Controller
    {
        private readonly ISpotifyClient spotify;

        public SuggestMusicController(ISpotifyClient spotifyClient)
        {
            this.spotify = spotifyClient;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Results(SuggestMusicViewModel model)
        {
            List<Track> recommendations = new List<Track>();
            string delimiter = ",";

            if (string.IsNullOrWhiteSpace(model.FavouriteArtistIds?.Replace(delimiter, string.Empty))
                && string.IsNullOrWhiteSpace(model.FavouriteTrackIds?.Replace(delimiter, string.Empty))
                && string.IsNullOrWhiteSpace(model.FavouriteGenres?.Replace(delimiter, string.Empty)))
            {
                ModelState.AddModelError("Model", "At least one question must be answered.");
            }

            string[] artistIds = model.FavouriteArtistIds?.Split(delimiter);
            string[] trackIds = model.FavouriteTrackIds?.Split(delimiter);
            string[] genreIds = model.FavouriteGenres?.Split(delimiter);

            if ((artistIds?.Count() ?? 0) + (trackIds?.Count() ?? 0) + (genreIds?.Count() ?? 0) > 5)
            {
                ModelState.AddModelError("Model", "Only 5 artist, track or genre items are allowed.");
            }
            else
            {
                await spotify.Authorize();
                IEnumerable<Track> tracks = await spotify.GetRecommendations(artistIds, trackIds, genreIds);
                if (tracks.Any())
                {
                    recommendations.AddRange(tracks);
                }
                else
                {
                    ModelState.AddModelError("Model", "No recommendations found.");
                }
            }

            if (!ModelState.IsValid)
            {
                return View(nameof(Index), model);
            }

            return View(recommendations);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SpotOn.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SpotOn.App</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">SpotOn.App</a>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - SpotOn.App</p>
        </footer>
    </div>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

SpotOn.App/Views/SuggestMusic/Index.cshtml
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
<link rel="stylesheet" href="~/lib/bootstrap-tagsinput/dist/bootstrap-tagsinput.css" />
<link rel="stylesheet" href="~/lib/bootstrap-tagsinput/dist/bootstrap-tagsinput-typeahead.css" />
<link rel="stylesheet" href="~/lib/typeahead.js-bootstrap3.less/typeaheadjs.css" />
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/typeahead.js/dist/typeahead.bundle.js"></script>
<script src="~/lib/bootstrap-tagsinput/dist/bootstrap-tagsinput.js"></script>

@{
    ViewData["Title"] = "Suggest music";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>


@model SpotOn.App.Models.SuggestMusicViewModel

<div class="container body-content">
    <div class="col-md-10">
        <section>
            @using (Html.BeginForm("Results", "SuggestMusic", FormMethod.Post))
            {
                <p>Please mind that total number of items must not exceed 5.</p>
                <p>
                    @Html.ValidationMessage("Model", new { @class = "text-danger" })
                </p>

                <label>What are your favourite genres?</label>

                <div class="form-group">
                    <div id="favgenres">
                        @Html.TextBoxFor(m => m.FavouriteGenres,
                        new
                        {
                            @class = "typeahead wide-control",
                            @data_role = "tagsinput"
                        })
                    </div>
                </div>

                <label>What are your favourite artists?</label>

                <div class="form-group">
                    <div id="favartists">
                        @Html.TextBoxFor(m => m.FavouriteArtistIds,
                        new
                        {
                            @class = "typeahead wide-control",
                            @data_role = "tagsinput"
                        })
                    </div>
                </div>

                <label>What are your favourite tracks?</label>

                <div class="form-group">
                    <div id="favtracks">
                        @Html.TextBoxFor(m => m.FavouriteTrackIds,
                        new
                        {
                            @class = "typeahead wide-control",
                            @data_role = "tagsinput"
                        })
                    </div>
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-default" id="submit">Submit</button>
                </div>
                }
        </section>
    </div>
</div>
<script>

    var genres = new Bloodhound({
        datumTokenizer: Bloodhound.tokenizers.obj.nonword('name'),
        queryTokenizer: Bloodhound.tokenizers.nonword,
        prefetch: '../api/Spotify/GetGenres'
    });

    $('#favgenres .typeahead').tagsinput({
        confirmKeys: [],
        itemValue: 'name',
        itemText: 'name',
        typeaheadjs: {
            limit: 25,
            name: 'genres',
            display: 'name',
            source: genres
        }
    });

    var artists = new Bloodhound({
        datumTokenizer: Bloodhound.tokenizers.obj.nonword('name'),
        queryTokenizer: Bloodhound.tokenizers.nonword,
        remote: {
            url: '../api/Spotify/FindArtists?input=%QUERY',
            wildcard: '%QUERY'
        }
    });

    $('#favartists .typeahead').tagsinput({
        confirmKeys: [],
        itemValue: 'id',
        itemText: 'name',
        typeaheadjs: {
            name: 'artists',
            display: 'name',
            source: artists
        }
    });

    var tracks = new Bloodhound({
        datumTokenizer: Bloodhound.tokenizers.obj.nonword('name'),
        queryTokenizer: Bloodhound.tokenizers.nonword,
        remote: {
            url: '../api/Spotify/FindTracks?input=%QUERY',
            wildcard: '%QUERY'
        }
    });

    $('#favtracks .typeahead').tagsinput({
        confirmKeys: [],
        itemValue: 'id',
        itemText: 'name',
        typeaheadjs: {
            name: 'tracks',
            display: 'displayName',
            source: tracks
        }
    });

</script>

SpotOn.App/Views/SuggestMusic/Results.cshtml
@model IEnumerable<SpotOn.Core.Track>

@{
    ViewData["Title"] = "Recommendations";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Results</title>
</head>
<body>
    <p>
        @Html.ActionLink("Try again", "Index")
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ArtistName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ArtistName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    <a href="@item.Url">Preview</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
</body>
</html>